server:
  port: 8761

eureka:
  instance:
    hostname: localhost
#    prefer-ip-address: true
  client:
    register-with-eureka: false # 表明自己是一个eureka server
    fetch-registry: false # 表明自己是一个eureka server
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  profiles:
    active: peer1
